name: parkirisca
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  permission_handler: ^8.3.0
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/map_style.txt
    - assets/icons/garage.png
    - assets/icons/parking.png
    - assets/icons/spot.png
    - assets/icons/rok.png
